FROM ubuntu:rolling@sha256:4a471b7df57f65d6aa7349409717152621a9efae3448d81de2619fc2d9b5b940
WORKDIR /app/stonks
# Install required packages
RUN apt update
RUN apt install -y libglib2.0-0
RUN apt install -y libnss3
RUN apt install -y libdbus-1-3
RUN apt install -y libatk1.0-0
RUN apt install -y libcups2
RUN apt install -y libdrm2
RUN apt install -y libatspi2.0-0
RUN apt install -y libxcomposite1
RUN apt install -y libxdamage1
RUN apt install -y libxfixes3
RUN apt install -y libxrandr2
RUN apt install -y libgbm1
RUN apt install -y libxkbcommon0
RUN apt install -y libpango-1.0-0
RUN apt install -y libcairo2
RUN apt install -y libasound2t64
RUN apt install -y xvfb
RUN apt install -y libatomic1
RUN apt install -y curl
# Install Volta package manager
RUN curl https://get.volta.sh | bash
ENV VOLTA_HOME="/root/.volta"
ENV PATH="$VOLTA_HOME/bin:$PATH"
RUN volta install node@22
# Install dependencies
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 5173
CMD ["npm", "run", "dev"]
