FROM ubuntu:rolling@sha256:2e863c44b718727c860746568e1d54afd13b2fa71b160f5cd9058fc436217b30
WORKDIR /app/nwjs
COPY ./node_modules/nw/nwjs-sdk-v0.90.0-linux-x64 .
RUN apt update
RUN apt install -y libglib2.0-0
RUN apt install -y libnss3
RUN apt install -y libdbus-1-3
RUN apt install -y libatk1.0-0
RUN apt install -y libcups2
RUN apt install -y libdrm2
RUN apt install -y libatspi2.0-0
RUN apt install -y libxcomposite1
RUN apt install -y libxdamage1
RUN apt install -y libxfixes3
RUN apt install -y libxrandr2
RUN apt install -y libgbm1
RUN apt install -y libxkbcommon0
RUN apt install -y libpango-1.0-0
RUN apt install -y libcairo2
RUN apt install -y libasound2t64
RUN apt install -y xvfb
RUN apt install -y libatomic1
CMD ["./nw"]
